export const PAGE_HEADER_CONTENT_HEIGHT_PX = 42;
export const PAGE_HEADER_PADDING_PX = 16;
export const PAGE_HEADER_BORDER_BOTTOM_WIDTH_PX = 1;

export const PAGE_HEADER_HEIGHT_PX = PAGE_HEADER_CONTENT_HEIGHT_PX + PAGE_HEADER_PADDING_PX * 2 + PAGE_HEADER_BORDER_BOTTOM_WIDTH_PX;
